/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visual;

import Clases.*;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author necoi
 */
public class BuscarPorCliente extends javax.swing.JInternalFrame {
    DefaultListModel<String> modeloLista = new DefaultListModel<>();
    /**
     * Creates new form BuscarPorCliente
     */
    public BuscarPorCliente() {
        initComponents();
        llenarListaTelefonos(-1L);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jlBusqueda = new javax.swing.JLabel();
        jlTeléfono = new javax.swing.JLabel();
        jtfBusquedaPorTel = new javax.swing.JTextField();
        jlApellido = new javax.swing.JLabel();
        jlDNI = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlCiudad = new javax.swing.JLabel();
        jlDomicilio = new javax.swing.JLabel();
        jtfDNI = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfCiudad = new javax.swing.JTextField();
        jtfDomicilio = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jspTelefonos = new javax.swing.JScrollPane();
        jlTelefonos = new javax.swing.JList<>();

        jlBusqueda.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlBusqueda.setText("Búsqueda por Clientes");

        jlTeléfono.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlTeléfono.setText("Teléfono:");

        jtfBusquedaPorTel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfBusquedaPorTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBusquedaPorTelActionPerformed(evt);
            }
        });
        jtfBusquedaPorTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBusquedaPorTelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBusquedaPorTelKeyTyped(evt);
            }
        });

        jlApellido.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlApellido.setText("Apellido:");

        jlDNI.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlDNI.setText("DNI:");

        jlNombre.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlNombre.setText("Nombre:");

        jlCiudad.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlCiudad.setText("Ciudad:");

        jlDomicilio.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlDomicilio.setText("Domicilio:");

        jtfDNI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDNIActionPerformed(evt);
            }
        });

        jtfApellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidoActionPerformed(evt);
            }
        });

        jtfNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jtfCiudad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCiudadActionPerformed(evt);
            }
        });

        jtfDomicilio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDomicilioActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jlTelefonos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlTelefonos.setName(""); // NOI18N
        jlTelefonos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlTelefonosValueChanged(evt);
            }
        });
        jspTelefonos.setViewportView(jlTelefonos);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jlTeléfono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jspTelefonos)
                            .addComponent(jtfBusquedaPorTel))
                        .addGap(30, 30, 30)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jlDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jlDomicilio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jlCiudad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jlNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jlApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jlBusqueda)
                                .addGap(261, 261, 261))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jbSalir)
                                .addGap(15, 15, 15))))))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlBusqueda)
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTeléfono)
                    .addComponent(jtfBusquedaPorTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDNI)
                    .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlApellido)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombre)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCiudad)
                            .addComponent(jtfCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDomicilio)
                            .addComponent(jtfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jspTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBusquedaPorTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBusquedaPorTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBusquedaPorTelActionPerformed

    private void jtfDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDNIActionPerformed

    private void jtfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApellidoActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCiudadActionPerformed

    private void jtfDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDomicilioActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jlTelefonosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlTelefonosValueChanged
        
        try { 
            //Recoge el valor seleccionado del JList
            String telSeleccionadoS = jlTelefonos.getSelectedValue();

            //Parsea el valor de String a Long
            Long telSeleccionado = Long.valueOf(telSeleccionadoS);

            //Agrega los valores en los jTextField
            int DNI = Menu.directorio.getClientela().get(telSeleccionado).getDni();
            jtfDNI.setText(""+DNI);
            jtfDNI.setEditable(false);

            String apellido = Menu.directorio.getClientela().get(telSeleccionado).getApellido();
            jtfApellido.setText(apellido);
            jtfApellido.setEditable(false);

            String nombre = Menu.directorio.getClientela().get(telSeleccionado).getNombre();
            jtfNombre.setText(nombre);
            jtfNombre.setEditable(false);

            String ciudad = Menu.directorio.getClientela().get(telSeleccionado).getCiudad();
            jtfCiudad.setText(ciudad);
            jtfCiudad.setEditable(false);

            String domicilio = Menu.directorio.getClientela().get(telSeleccionado).getDireccion();
            jtfDomicilio.setText(domicilio);
            jtfDomicilio.setEditable(false);
        
        } catch (NumberFormatException e) {
            
            System.out.println("Casilla vacia");
            
        }
    }//GEN-LAST:event_jlTelefonosValueChanged

    private void jtfBusquedaPorTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBusquedaPorTelKeyTyped

    }//GEN-LAST:event_jtfBusquedaPorTelKeyTyped

    private void jtfBusquedaPorTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBusquedaPorTelKeyReleased
        try {
            Long textoCreandose = -1L;
            //Texto creandose en base a cada letra que se teclea
            if(!jtfBusquedaPorTel.getText().isEmpty())
            {
               textoCreandose = Long.valueOf(jtfBusquedaPorTel.getText()); 
            }
            

            //Crea nueva Lista con lo ingresado        
            llenarListaTelefonos(textoCreandose);

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Debe colocar el formato correcto");
            jtfBusquedaPorTel.setText("");
        }
    }//GEN-LAST:event_jtfBusquedaPorTelKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlBusqueda;
    private javax.swing.JLabel jlCiudad;
    private javax.swing.JLabel jlDNI;
    private javax.swing.JLabel jlDomicilio;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JList<String> jlTelefonos;
    private javax.swing.JLabel jlTeléfono;
    private javax.swing.JScrollPane jspTelefonos;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfBusquedaPorTel;
    private javax.swing.JTextField jtfCiudad;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JTextField jtfDomicilio;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
    private void llenarListaTelefonos(Long telBusqueda) {
        
            //Se limpia jlTelefonos (JList)
            modeloLista.clear();
            
            jlTelefonos.setModel(modeloLista);
            for (Long tel : Menu.directorio.getClientela().keySet()) {

                //Por un lado si telBusqueda es menor a 0 va a brindar todos los números 
                //Si se ha buscado por número, entonces la lista se llenará unicamente con dichos telefonos
                if (compararLong(telBusqueda, tel)) {
                    modeloLista.addElement(Long.toString(tel));
                }

            }
            
           
    }
    
    //Es un comparador del teléfono ingresado por jtfBusquedaPorTel, si da true, entonces coincide el número ingresado
    private boolean compararLong(Long busqueda, Long buscado) {
        
        String busquedaS = Long.toString(busqueda);
        String buscadoS = Long.toString(buscado);
        int contador = 0;
        if(busqueda < 0) {
            return true;
        } else {
            try {

                for (int i = 0; i < busquedaS.length(); i++) {

                    if (buscadoS.charAt(i) == busquedaS.charAt(i)) {
                        contador++;
                    }
                }

                if (contador == busquedaS.length()) {

                    return true;

                } else {

                    return false;

                }

            } catch (ArrayIndexOutOfBoundsException | StringIndexOutOfBoundsException e) {
                return false;
            }  
            
        }


        
   
    }
    
    

}
