/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

/**
 *
 * @author Agustin
 */
public class Directorio extends javax.swing.JFrame {

    /**
     * Creates new form Directorio
     */
    public Directorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jmMenu = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiAgregarCliente = new javax.swing.JMenuItem();
        jmiBuscarCliente = new javax.swing.JMenuItem();
        jmiBorrarCliente = new javax.swing.JMenuItem();
        jmDirectorio = new javax.swing.JMenu();
        jmiBuscarClientePorCiudad = new javax.swing.JMenuItem();
        jmiBuscarClientePorApellido = new javax.swing.JMenuItem();
        jmCiudades = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        jmClientes.setText("Clientes");

        jmiAgregarCliente.setText("Agregar Cliente");
        jmiAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiAgregarCliente);

        jmiBuscarCliente.setText("Buscar Cliente");
        jmiBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBuscarCliente);

        jmiBorrarCliente.setText("Borrar Cliente");
        jmClientes.add(jmiBorrarCliente);

        jmMenu.add(jmClientes);

        jmDirectorio.setText("Directorio");

        jmiBuscarClientePorCiudad.setText("Buscar cliente por Ciudad");
        jmiBuscarClientePorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarClientePorCiudadActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmiBuscarClientePorCiudad);

        jmiBuscarClientePorApellido.setText("Buscar cliente por Apellido ");
        jmiBuscarClientePorApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarClientePorApellidoActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmiBuscarClientePorApellido);

        jmMenu.add(jmDirectorio);

        jmCiudades.setText("Ciudades");

        jMenuItem3.setText("jMenuItem3");
        jmCiudades.add(jMenuItem3);

        jmMenu.add(jmCiudades);

        jmSalir.setText("Salir");
        jmMenu.add(jmSalir);

        setJMenuBar(jmMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAgregarClienteActionPerformed

    private void jmiBuscarClientePorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarClientePorCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiBuscarClientePorCiudadActionPerformed

    private void jmiBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiBuscarClienteActionPerformed

    private void jmiBuscarClientePorApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarClientePorApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiBuscarClientePorApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Directorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Directorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Directorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Directorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Directorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jmCiudades;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmDirectorio;
    private javax.swing.JMenuBar jmMenu;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAgregarCliente;
    private javax.swing.JMenuItem jmiBorrarCliente;
    private javax.swing.JMenuItem jmiBuscarCliente;
    private javax.swing.JMenuItem jmiBuscarClientePorApellido;
    private javax.swing.JMenuItem jmiBuscarClientePorCiudad;
    // End of variables declaration//GEN-END:variables
}
