/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Clases.Directorio;
import java.util.ArrayList;

/**
 *
 * @author Agustin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Directorio
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jmMenu = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiAgregarCliente = new javax.swing.JMenuItem();
        jmiBuscarCliente = new javax.swing.JMenuItem();
        jmiBorrarCliente = new javax.swing.JMenuItem();
        jmDirectorio = new javax.swing.JMenu();
        jmiBuscarClientePorCiudad = new javax.swing.JMenuItem();
        jmiBuscarClientePorApellido = new javax.swing.JMenuItem();
        jmCiudades = new javax.swing.JMenu();
        jmiAgregarCiudad = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jmClientes.setText("Clientes");

        jmiAgregarCliente.setText("Agregar Cliente");
        jmiAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiAgregarCliente);

        jmiBuscarCliente.setText("Buscar Cliente");
        jmiBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarClienteActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBuscarCliente);

        jmiBorrarCliente.setText("Borrar Cliente");
        jmClientes.add(jmiBorrarCliente);

        jmMenu.add(jmClientes);

        jmDirectorio.setText("Directorio");

        jmiBuscarClientePorCiudad.setText("Buscar cliente por Ciudad");
        jmiBuscarClientePorCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarClientePorCiudadActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmiBuscarClientePorCiudad);

        jmiBuscarClientePorApellido.setText("Buscar cliente por Apellido ");
        jmiBuscarClientePorApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarClientePorApellidoActionPerformed(evt);
            }
        });
        jmDirectorio.add(jmiBuscarClientePorApellido);

        jmMenu.add(jmDirectorio);

        jmCiudades.setText("Ciudades");

        jmiAgregarCiudad.setText("Agregar Ciudad");
        jmiAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarCiudadActionPerformed(evt);
            }
        });
        jmCiudades.add(jmiAgregarCiudad);

        jmMenu.add(jmCiudades);

        jmSalir.setText("Salir");

        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmSalir.add(jmiExit);

        jmMenu.add(jmSalir);

        setJMenuBar(jmMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarClienteActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        VistaCliente vc= new VistaCliente();
        vc.setVisible(true);
        jdpEscritorio.add(vc);
        jdpEscritorio.moveToFront(vc);
    }//GEN-LAST:event_jmiAgregarClienteActionPerformed

    private void jmiBuscarClientePorCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarClientePorCiudadActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        BuscarPorCiudad bc= new BuscarPorCiudad();
        bc.setVisible(true);
        jdpEscritorio.add(bc);
        jdpEscritorio.moveToFront(bc);
    }//GEN-LAST:event_jmiBuscarClientePorCiudadActionPerformed

    private void jmiBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarClienteActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        BuscarPorCliente bc= new BuscarPorCliente();
        bc.setVisible(true);
        jdpEscritorio.add(bc);
        jdpEscritorio.moveToFront(bc);
    }//GEN-LAST:event_jmiBuscarClienteActionPerformed

    private void jmiBuscarClientePorApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarClientePorApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiBuscarClientePorApellidoActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarCiudadActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        AgregarCiudad vi = new AgregarCiudad();
        vi.setVisible(true);
        jdpEscritorio.add(vi);
        jdpEscritorio.moveToFront(vi);
    }//GEN-LAST:event_jmiAgregarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    public static Directorio directorio = new Directorio();
    public static ArrayList<String> ciudades = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmCiudades;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmDirectorio;
    private javax.swing.JMenuBar jmMenu;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAgregarCiudad;
    private javax.swing.JMenuItem jmiAgregarCliente;
    private javax.swing.JMenuItem jmiBorrarCliente;
    private javax.swing.JMenuItem jmiBuscarCliente;
    private javax.swing.JMenuItem jmiBuscarClientePorApellido;
    private javax.swing.JMenuItem jmiBuscarClientePorCiudad;
    private javax.swing.JMenuItem jmiExit;
    // End of variables declaration//GEN-END:variables
}
